server:
  port: 8080
  mode: release # Can be debug or release

database:
  type: sqlite
  name: gonav.db
  path: "./data/" # Create database file in backend/data directory

cors:
  allowOrigins:
    - "http://localhost:3000"
    - "http://127.0.0.1:3000"

jwt:
  secret: "your_secret_key" # Please use a more secure key
  expirationHours: 24 # JWT token expiration time (hours)